defmodule Infoloop.Repo.Migrations.GoogleAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :picture, :text
    end
  end

  def down do
    alter table(:users) do
      remove :picture
      remove :last_name
      remove :first_name
    end
  end
end
