defmodule Infoloop.Repo.Migrations.AddPointsToCompletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:completions) do
      add :status, :text, default: "missing"
      add :points, :bigint
    end
  end

  def down do
    alter table(:completions) do
      remove :points
      remove :status
    end
  end
end
