defmodule Infoloop.Repo.Migrations.BonusPointsAssignments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assignments) do
      add :bonus, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:assignments) do
      remove :bonus
    end
  end
end
