defmodule Infoloop.Repo.Migrations.DatabaseStruct do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_classes, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "user_classes_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :class_id, :uuid, null: false, primary_key: true
    end

    create table(:completions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :user_id,
          references(:users,
            column: :id,
            name: "completions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :assignment_id,
          references(:assignments,
            column: :id,
            name: "completions_assignment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:classes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:user_classes) do
      modify :class_id,
             references(:classes,
               column: :id,
               name: "user_classes_class_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:classes) do
      add :title, :text, null: false
      add :archived, :boolean, null: false, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :teacher_id,
          references(:users,
            column: :id,
            name: "classes_teacher_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:assignments) do
      add :class_id,
          references(:classes,
            column: :id,
            name: "assignments_class_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:assignments, "assignments_class_id_fkey")

    alter table(:assignments) do
      remove :class_id
    end

    drop constraint(:classes, "classes_teacher_id_fkey")

    alter table(:classes) do
      remove :teacher_id
      remove :updated_at
      remove :inserted_at
      remove :archived
      remove :title
    end

    drop constraint(:user_classes, "user_classes_class_id_fkey")

    alter table(:user_classes) do
      modify :class_id, :uuid
    end

    drop table(:classes)

    drop constraint(:completions, "completions_user_id_fkey")

    drop constraint(:completions, "completions_assignment_id_fkey")

    drop table(:completions)

    drop constraint(:user_classes, "user_classes_user_id_fkey")

    drop table(:user_classes)
  end
end
