defmodule Infoloop.Repo.Migrations.AddDescriptionToClass do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:classes) do
      add :description, :text
    end
  end

  def down do
    alter table(:classes) do
      remove :description
    end
  end
end
